// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  devOpsSidebar: [
    // "intro",
    {
      type: "category",
      label: "DevOps",
      link: {
        type: "doc",
        id: "index",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Docker",
          link: {
            type: "doc",
            id: "docker/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "docker/docker-fundamentals",
              label: "Docker Fundamentals",
            },
            {
              type: "doc",
              id: "docker/mounts-and-volumes",
              label: "Mounts and Volumes",
            },
            {
              type: "doc",
              id: "docker/docker-compose",
              label: "Docker Compose",
            },
            {
              type: "doc",
              id: "docker/compose-instructions",
              label: "Compose Instructions",
            },
            {
              type: "doc",
              id: "docker/commands",
              label: "Docker Commands",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;


// "docker/docker-fundamentals",
// "docker/mounts-and-volumes",
// "docker/docker-compose",
// "docker/compose-instructions",
// "docker/commands",