// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  mongoDBSidebar: [
    {
      type: "category",
      label: "MongoDB",
      link: {
        type: "doc",
        id: "index",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "concepts-and-architecture",
          label: "Concepts and Architecture",
        },
        {
          type: "doc",
          id: "operators-reference",
          label: "Operators Reference",
        },
        {
          type: "category",
          label: "Practice Questions",
          link: {
            type: "doc",
            id: "practice-questions",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "beginner-aggregation",
              label: "Beginner level questions",
            },
            {
              type: "doc",
              id: "intermediate-aggregation",
              label: "Intermediate level questions",
            },
            {
              type: "doc",
              id: "advanced-aggregation",
              label: "Advanced level questions",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
