// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  reactJSSidebar: [
    // "intro",
    {
      type: "category",
      label: "React JS",
      link: {
        type: "doc",
        id: "index",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Prerequisites",
          link: {
            type: "doc",
            id: "prerequisites/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "prerequisites/dom-manipulation",
              label: "DOM Manipulation",
            },
            {
              type: "doc",
              id: "prerequisites/es6-features",
              label: "ES6+ JavaScript",
            },
            {
              type: "doc",
              id: "prerequisites/async-javascript",
              label: "Promises & Async/Await",
            },
          ],
        },
        {
          type: "category",
          label: "Foundations",
          link: {
            type: "doc",
            id: "foundations/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "foundations/virtual-vs-real-dom",
              label: "Virtual vs Real DOM",
            },
            {
              type: "doc",
              id: "foundations/components",
              label: "Components",
            },
            {
              type: "doc",
              id: "foundations/state",
              label: "State",
            },
            {
              type: "doc",
              id: "foundations/rendering",
              label: "Re-rendering",
            },
          ],
        },
        {
          type: "category",
          label: "Hooks",
          link: {
            type: "doc",
            id: "hooks/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "hooks/useState",
              label: "useState",
            },
            {
              type: "doc",
              id: "hooks/useEffect",
              label: "useEffect",
            },
            {
              type: "doc",
              id: "hooks/useMemo",
              label: "useMemo",
            },
            {
              type: "doc",
              id: "hooks/useCallback",
              label: "useCallback",
            },
            {
              type: "doc",
              id: "hooks/useRef",
              label: "useRef",
            },
            {
              type: "doc",
              id: "hooks/useReducer",
              label: "useReducer",
            },
            {
              type: "doc",
              id: "hooks/useContext",
              label: "useContext",
            },
            {
              type: "doc",
              id: "hooks/useLayoutEffect",
              label: "useLayoutEffect",
            },
            {
              type: "doc",
              id: "hooks/custom-hooks",
              label: "Custom Hooks",
            },
            {
              type: "doc",
              id: "hooks/common-mistakes",
              label: "Common Mistakes",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced Guides",
          link: {
            type: "doc",
            id: "advanced-guides/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "advanced-guides/side-effects-guide",
              label: "Side Effects",
            },
            {
              type: "doc",
              id: "advanced-guides/wrapper-components",
              label: "Wrapper Components",
            },
            {
              type: "doc",
              id: "advanced-guides/props-drilling",
              label: "Props Drilling",
            },
            {
              type: "doc",
              id: "advanced-guides/performance-js",
              label: "Debouncing & Throttling",
            },
          ],
        },
        {
          type: "category",
          label: "State Management",
          link: {
            type: "doc",
            id: "state-management/index",
          },
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "state-management/redux",
              label: "Redux",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
